[workspace]
members = [
	#"factor-example",
	"native-kernel-converter",
	"stark-aggregation/guest",
	"stark-aggregation/host",
	#"halo2-aggregation",
	#"asm"
	]
resolver = "2"

[workspace.dependencies]
p3-field = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
openvm-stark-sdk = { git = "https://github.com/openvm-org/stark-backend.git", rev = "47a0bda" }

snark-verifier-sdk = { git = "https://github.com/axiom-crypto/snark-verifier", branch = "zkvm-v0.1", default-features = false, features = [
    "loader_halo2",
    "halo2-axiom",
    "display",
] }
halo2curves-axiom = { version = "0.5.3" } 

openvm = { git = "https://github.com/scroll-tech/openvm", branch = "scroll-dev-0121", features = ["std"] }
openvm-native-recursion = { git = "https://github.com/scroll-tech/openvm", branch = "scroll-dev-0121" }
openvm-sdk = { git = "https://github.com/scroll-tech/openvm", branch = "scroll-dev-0121", default-features = false}
openvm-circuit = { git = "https://github.com/scroll-tech/openvm", branch = "scroll-dev-0121" }
openvm-instructions ={ git = "https://github.com/scroll-tech/openvm", branch = "scroll-dev-0121" }
openvm-native-compiler = { git = "https://github.com/scroll-tech/openvm", branch = "scroll-dev-0121" }
openvm-rv32im-transpiler = { git = "https://github.com/scroll-tech/openvm", branch = "scroll-dev-0121" }


serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0" }
serde_with = "3.11.0"
bitcode = { version = "0.6.3", default-features = false, features = ["serde", "derive"] }
derivative = "2.2.0"
toml = "0.8.14"

