[package]
name = "stark-aggregation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#openvm = { git = "https://github.com/openvm-org/openvm.git", rev = "074cb83", features = ["std"] }
openvm = { path = "/home/ubuntu/zzhang/openvm/crates/toolchain/openvm", features = ["std"] }

halo2curves-axiom = { version = "0.5.3" } 

